# Generated by Django 4.1.6 on 2023-03-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='tittle',
        ),
    ]
