# Generated by Django 4.1.6 on 2023-03-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tittle',
        ),
    ]
