# Generated by Django 4.1.6 on 2023-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add',
        ),
        migrations.DeleteModel(
            name='file',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(default=2, max_length=222),
            preserve_default=False,
        ),
    ]
