# Generated by Django 4.1.6 on 2023-04-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password',
        ),
    ]
