# Generated by Django 4.1.6 on 2023-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_delete_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavecomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adds_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
    ]
