# Generated by Django 4.1.6 on 2023-05-10 07:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_leavecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
