# Generated by Django 4.1.6 on 2023-05-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(max_length=222),
        ),
    ]
